{
	"version": 1528781053,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/object-sheet0.png",
		"images/player-sheet0.png",
		"images/instructions-sheet0.png",
		"images/door-sheet0.png",
		"images/light-sheet0.png",
		"images/lighton-sheet0.png",
		"images/2ndbackground-sheet0.png",
		"images/cave-sheet0.png",
		"images/floorof-sheet0.png",
		"images/untitled-sheet0.png",
		"images/cavefloor-sheet0.png",
		"images/cavebackgroundtop-sheet0.png",
		"images/cavebackground-sheet0.png",
		"images/cavetrigger-sheet0.png",
		"images/vincjgx3fkqofqhkxveowau7afgqhafyifadqzqp7y-sheet0.png",
		"images/darkswitch-sheet0.png",
		"images/backgroundfordark-sheet0.png",
		"images/door2-sheet0.png",
		"images/white-sheet0.png",
		"media/teleport.m4a",
		"media/teleport.ogg",
		"media/background sounds.m4a",
		"media/background sounds.ogg",
		"media/untitled.m4a",
		"media/untitled.ogg",
		"media/concrete.m4a",
		"media/concrete.ogg",
		"media/door.m4a",
		"media/door.ogg",
		"media/rocks falling.m4a",
		"media/rocks falling.ogg",
		"media/jump 1.m4a",
		"media/jump 1.ogg",
		"media/dash sound.m4a",
		"media/dash sound.ogg",
		"media/walkingwoods.m4a",
		"media/walkingwoods.ogg",
		"media/forest sounds.m4a",
		"media/forest sounds.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"csgo.webm"
	]
}